image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

before_build:
  - choco install opencover.portable
  - choco install codecov
  - dotnet restore

build:
  project: WebApi.Models.sln

test_script:
  - OpenCover.Console.exe -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full WebApi.Models.Tests\WebApi.Models.Tests.csproj" -filter:"+[WebApi.Models*]* -[WebApi.Models.Tests*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: WebApi.Models\bin\Release\netstandard2.0\WebApi.Models.dll
    name: WebApi.Models.dll
  - path: WebApi.Models\bin\Release\WebApi.Models.%version%.nupkg
    name: WebApi.Models.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: hkXpIUpYzUNo2MK2cFEolTq/lHA5v14G0Ew4ZhTAYSHd8Fcpy5u89rfJGQzk4LV3
